# Generated by Django 3.1 on 2020-08-17 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuser',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='testuser',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
