# Generated by Django 3.1 on 2020-08-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200817_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
