# Generated by Django 3.1 on 2020-08-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200817_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='photo',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='images', verbose_name='Фото', width_field=200),
        ),
    ]
