# Generated by Django 3.1 on 2020-08-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200817_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Фото'),
        ),
    ]
