# Generated by Django 3.1 on 2020-08-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200817_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='photo',
            field=models.ImageField(blank=True, default='images/default_profile.png', null=True, upload_to='images', verbose_name='Фото'),
        ),
    ]
