# Generated by Django 3.1 on 2020-08-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='result',
            field=models.FloatField(verbose_name='Результат (процентов)'),
        ),
    ]
