# Generated by Django 3.1 on 2020-08-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200819_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
